README.md

JS code is now integrated into this repo, in `/media/src`.

Remove outdated setup info

---

package.json
rollup.config.js

Also, re-format this file to our standard 4-spaces format.

Add eslint checking for rollup config

---

media/src/App.svelte

Removed some unnecessary things and re-organized the steps here. This appears to improve performance.

Make some shader adjustments for performance - #97

---

media/src/App.svelte
media/src/Room.svelte
media/src/rooms.js

When two clients are at the `/rooms/1/` route, for example, new object creation events are shared over websockets.
This is just a very basic skeleton in place - lots to figure out from here.

Allow room participants to receive new box data

---

media/src/App.svelte
media/src/Chapter.svelte
media/src/Curve.svelte
media/src/Field.svelte
media/src/Function.svelte
media/src/Intro.svelte
media/src/Level.svelte
media/src/ParSurf.svelte
media/src/Polls.svelte
media/src/Vector.svelte
media/src/rooms.js
media/src/utils.js

cleanup: Remove console.log statements

---

media/src/App.svelte
media/src/sceneUtils.js

Parameterize the state to make these stateless functions, which is best practice and makes them more testable in unit tests

Refactor scene drawing functions into sceneUtils.js

---

mathplayground/main/tests/test_views.py
mathplayground/smoke.py

This should fix the hound failure.

Add basic smoketest

---

package-lock.json
package.json
rollup.config.mjs

Use @rollup/plugin-terser to minify JS build.
https://github.com/TrySound/rollup-plugin-terser/pull/120#issuecomment-1293931238

Add new rollup-terser plugin

---

mathplayground/rooms/consumers.py
mathplayground/rooms/scene.py
media/src/App.svelte
media/src/objects/Vector.svelte
media/src/sceneUtils.js

Update the scene and participants when an object is updated.
Only working with the Vector object so far.
TODO:
* Add onUpdate() handlers to the rest of the objects.
* Add unit tests for the new updateObject functions on frontend + backend

Implement updateObject event

---

rollup.config.mjs

This may help alleviate the compile time issue (#136)

Turn off a few rollup options in dev mode

---

media/src/App.svelte
media/src/objects/Box.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/ParSurf.svelte
media/src/sceneUtils.js
media/test/sceneUtils.test.js

* Added unit test
* Hook up the new update event to more object types: 
** Box
** Curve
** Vector Field (this requires more work to get animation working) 
** Function Graph
** Parametric Surface

Add more updateObject functionality

---

media/src/App.svelte
media/src/objects/Level.svelte

Update redis + websockets clients when levelSurface has changed.

Add update functionality for levelSurface

---

media/src/App.svelte

Convert raise-lower-bar to boostrap button for accessibility

---

media/src/Intro.svelte

I changed this to a bootstrap button.

Fix intro button's readability

---

media/src/App.svelte
media/src/modes/Session.svelte

I'm using too many different terms here. Let's try and stick with "room". Session already means something else in the backend.

Use "Room" instead of "Session" in session joiner

---

mathplayground/rooms/consumers.py
media/mathplayground/global.css
media/src/App.svelte
media/src/Poll.svelte
media/src/Polls.svelte
media/src/Settings.svelte
media/src/modes/Session.svelte
media/src/pollUtils.js
media/src/rooms.js
media/src/stores.js
media/test/pollUtils.test.js

Just laying out basic UI for multiple choice quizzes so far:

Add basic "broadcast poll" functionality

---

README.md

This application does require some special nginx setup, which is kind of annoying. It's an argument for developing with something like [docker](https://www.docker.com/) or [vagrant](https://www.vagrantup.com/), where we could specify this configuration within the code here. I just don't personally use those tools.

Add nginx config notes

---

media/src/App.svelte

We can adjust pan and rotation speed as necessary.
* https://github.com/mrdoob/three.js/pull/24974
* https://threejs.org/docs/#examples/en/controls/OrbitControls

Allow camera to be controlled by arrow keys

---

mathplayground/rooms/consumers.py
media/src/App.svelte
media/src/sceneUtils.js

This adds a working "Publish Scene" button to the objects editor, and
removes the automatic scene updating from happening on every change.
The code for that is still in place, if we want to use it in the future.

Add Publish Scene feature

---

media/src/objects/Curve.svelte

Minor tweak, but I was tired of how illegible the Space Curve text was sometimes.

Made Space Curve title white, so it's more readable

---

media/mathplayground/global.css
media/src/d3/BarChart.js
media/src/d3/Histogram.js
media/src/polls/PollResponses.svelte
media/src/polls/Polls.svelte

There's still more to figure out here, but this gets the basic system in place, and allows for assigning multiple polls.

add d3 Histogram for numerical poll type

---

mathplayground/rooms/consumers.py
media/src/App.svelte

Save/load poll to redis when appropriate.

Make currentPoll persistent

---

requirements.txt

Not sure why dependabot didn't pick up this update automatically

:arrow_up: django 4.1.5

---

mathplayground/templates/index.html

There can't be a script tag outside of the `<head>` or `<body>` tags.

Fix GA tag script

---

mathplayground/rooms/consumers.py
mathplayground/rooms/scene.py
mathplayground/templates/index.html
media/src/App.svelte
media/src/modes/Session.svelte
media/src/rooms.js

Store session key in redis to differentiate host vs student depending on room creation.

Implement new feature: User becomes room host on "Make Room"

---

media/src/App.svelte

Replace this with a Session toggle button.

Remove Modes dropdown

---

media/mathplayground/global.css
media/src/ObjHeader.svelte

* Add button titles for accessibility / usability
* Re-organize CSS class to apply to the common surrounding div and use specific CSS selectors

Make a few ObjHeader adjustments

---

media/src/App.svelte

This was leftover and I meant to remove it with an earlier change.

Remove Modes dropdown from Objects menu

---

media/src/App.svelte

Make title a link to the main page.

Add Home link

---

mathplayground/rooms/consumers.py

When a websockets connection is made or destroyed, record the user's unique session key in an instance object that we can use to determine how many users are connected to a room.

Record "active users" in django-channels - #265

---

mathplayground/rooms/consumers.py
media/src/App.svelte

Implement active user count UI

---

mathplayground/main/views.py
mathplayground/settings.py
requirements.txt

The GA code wasn't coming through in the room template, and I realized we have this library to automatically add this variable to all views.
https://github.com/ccnmtl/django-ga-context

Use django-ga-context library to add GA_CODE to all views

---

media/src/App.svelte
media/src/objects/Curve.svelte

When a Space Curve or Vector Field is saved in the animating state, users joining the room will see it in the animating state. They can then stop it on their own if they want.
The next steps here are live animated state on scene publish.

Implement animation in saved scene state

---

media/src/App.svelte

per Drew's notes, I guess we will hide the Chapters section until #287 is merged.

Hide Chapters dropdown

---

media/src/App.svelte
media/src/Chapter.svelte
media/src/KeyboardControls.svelte
media/src/objects/Curve.svelte
media/src/objects/Vector.svelte
rollup.config.mjs

Used z-index to fix overlapping element conflicts
Bump eslint-plugin-svelte from 2.14.1 to 2.15.0
Bumps [eslint-plugin-svelte](https://github.com/ota-meshi/eslint-plugin-svelte) from 2.14.1 to 2.15.0.
- [Release notes](https://github.com/ota-meshi/eslint-plugin-svelte/releases)
- [Changelog](https://github.com/ota-meshi/eslint-plugin-svelte/blob/main/CHANGELOG.md)
- [Commits](https://github.com/ota-meshi/eslint-plugin-svelte/compare/v2.14.1...v2.15.0)
---
updated-dependencies:
- dependency-name: eslint-plugin-svelte dependency-type: direct:development update-type: version-update:semver-minor ...
Signed-off-by: dependabot[bot] <support@github.com>
Bump coverage from 7.0.0 to 7.1.0
Bumps [coverage](https://github.com/nedbat/coveragepy) from 7.0.0 to 7.1.0.
- [Release …

Cleaned up Chapter formatting and functionality

---

media/src/modes/Session.svelte
media/src/rooms.js

Also, error in JS console if there is no socket present on setHost.

Expand room IDs to 1 to 1000.

---

mathplayground/rooms/consumers.py

An empty array is considered False in this if statement - be more lenient here.

Fix bug where host is not set on empty room creation

---

.eslintrc.js
media/src/App.svelte
media/src/Settings.svelte

Improved switching between camera views.

Consistent camera

---

mathplayground/rooms/tests/test_views.py

The chrome driver recently started failing:
> selenium.common.exceptions.WebDriverException: Message: unknown error:
> unable to discover open pages

Use firefox driver in selenium testing

---

media/src/App.svelte
media/src/KeyboardControls.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/ParSurf.svelte
media/src/objects/Vector.svelte

Parametric surface needs some work in order to render the tangent plane and normal vector. Specifically some sort of conversion between the uv values and the xyz values. Threejs objects do have uv attributes so this might not be too hard, but I'm setting it as a separate issue. https://github.com/ccnmtl/mathplayground/issues/348

Keyboard functions added to all objects

---

mathplayground/rooms/scene.py

Clear redis room data after 24 hours

---

requirements.txt

We can test out the new beta version of 4.2. The final release will happen soon.
https://docs.djangoproject.com/en/dev/releases/4.2/

:arrow_up: django 4.2b1

---

media/src/rooms.js
package-lock.json
package.json

Use this simple library on top of WebSocket that automatically reconnects on failure.
https://github.com/pladaria/reconnecting-websocket
related issue: #380

Introduce ReconnectingWebSocket

---

media/src/App.svelte

https://svelte.dev/tutorial/keyed-each-blocks

Use uuid as key in objects each block

---

media/src/objects/Function.svelte
media/src/objects/Level.svelte

This fixes the inputs to display with bootstrap styles.

Add missing form-control class to a few param inputs

---

media/src/App.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Level.svelte
media/src/objects/ParSurf.svelte
media/src/objects/Vector.svelte

Add scene selection to the rest of the object types

---

media/src/App.svelte

👆🏻
I find myself turning it off manually more often than not. YMMV.

Turn off grid by default

---

media/mathplayground/global.css

Revert to the Bootstrap default here
(https://getbootstrap.com/docs/5.3/content/reboot/#native-font-stack)
Any custom font changes we want to make should happen in a unified way, and will be handled by Marc.

Remove custom font families

---

media/src/objects/Field.svelte

Cosmetic:
- Vectors felt too big. 
- Changed trailColor from fading to white which looked weird on the background to fading to the complementary color in hsl space. Maybe a bit much.
Bugs:
- Remade silly precompute-geometries-with-different-lengths idea to just `adjustHeight` on each. 
- trailColors change with color change even when paused
Features:
- added (r)ewind keyboard shortcut

Touch up length, size, and color

---

media/src/App.svelte

Makes loop logic tighter and makes the props for each 3DObject component uniform.

Compactify if-else logic in main loop

---

media/src/App.svelte
media/src/objects/Point.svelte

Add a `Point` component. Can be moved with `t` dependence.

Add point component

---

media/src/objects/Curve.svelte

Was normalizing velocity before calculating speed.

Fix reparamatrization by s

---

.editorconfig
media/src/App.svelte
media/src/objects/Curve.svelte
media/src/objects/Function.svelte
media/src/objects/Point.svelte
media/src/objects/Vector.svelte

This expanded a little from the original mission as I found a lot of bugs around animating vectors, curves, and points. 
Should test further before merging, publish scenes with animating elements, and let me know if something misfires.

Restore level animation / shore up animation-from-start

---

mathplayground/rooms/consumers.py
media/src/App.svelte
media/src/session/Chatroom.svelte
media/src/session/Session.svelte

Add basic student -> host chat

---

mathplayground/templates/index.html
media/mathplayground/global.css
media/src/App.svelte
media/src/Panel.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/ParSurf.svelte
media/src/objects/Point.svelte
media/src/objects/Vector.svelte
media/src/polls/Polls.svelte
media/src/settings/Settings.svelte

This major refactor puts all the form components and text parts of the app inside a new Panel component.
Next steps:
* Add button to toggle hide/show state for Panel
* Possibly separate Object List from "content" area, each in their own boxes

Introduce resizable Panel

---

media/mathplayground/global.css
media/src/Panel.svelte
media/src/objects/Field.svelte
media/src/objects/Point.svelte
media/src/objects/Vector.svelte

Fix a bug with the t-display on `Point` and `Vector`. 
Update `Field` to play at initialization/publish scene. 
I know we don't usually pull to other branches. Didn't want to leapfrog `panel`

Anim panel check

---

media/src/App.svelte
media/src/polls/Poll.svelte
media/src/session/Session.svelte

closes #407
Also, change isHost to standard component param. Two-way bindings should only be used when really necessary.

Don't display poll question if I'm the host

---

mathplayground/templates/index.html
media/src/App.svelte
media/src/settings/Settings.svelte

v4 is old, and the latest is v6. A few of the icon names have changed here: https://fontawesome.com/v5/search

:arrow_up: fontawesome 5.15.4

---

requirements.txt

Revert "Bump cryptography from 39.0.0 to 40.0.0"

---

requirements.txt

https://github.com/redis/redis-py/releases/tag/v4.5.3

:arrow_up: redis 4.5.3

---

media/src/Panel.svelte

I put together a custom CSS button here with some panel transitions.
closes #482

Implement Panel hider button

---

media/src/App.svelte
media/src/Panel.svelte

We are keeping this visually removed from the panel after all.

Move settings tray out of Panel

---

media/src/App.svelte
media/src/Panel.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/Surface.svelte
media/src/objects/Vector.svelte
media/src/polls/Poll.svelte
media/src/polls/PollResponses.svelte
media/src/polls/Polls.svelte
media/src/session/Session.svelte
media/src/settings/Settings.svelte

selectedPoint was relevant because under the current implementation points are not associated with their corresponding objects. They are simply added into the scene.

Pinpoint-poll rebase

---

mathplayground/templates/index.html
media/src/App.svelte
media/src/Panel.svelte

The poll view should be visible when the user receives a poll, whatever state the application is in.

On poll receive, display poll

---

objectExamples/nVectorExample.json

This is a sample of the new multi-vector, time dependent feature for `Vector` objects

nVectorExample JSON

---

media/src/App.svelte
media/src/Panel.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/ObjHeader.svelte
media/src/objects/Point.svelte
media/src/objects/Solid.svelte
media/src/objects/Surface.svelte
media/src/objects/Vector.svelte

As discussed w/ Drew, use the `dblclick` event to select an object.
Also, use title link in object form to select object rather than clicking the obj form, as it's more standard web behavior.
Closes #441

Use double-click to select object

---

media/src/App.svelte

Following this example here:
https://threejs.org/examples/webgl_postprocessing_outline.html

Display three.js outline on selected object

---

media/src/App.svelte
media/src/objects/Solid.svelte
media/src/sceneUtils.js

Make `Solid` objects selectable by mouse click.
The problem was the EdgesGeometry for the borders. Just left it out of the list of intersection objects.
Fixes #525.

Make solid selectable

---

media/src/App.svelte
media/src/objects/Solid.svelte
media/src/sceneUtils.js

Broke the coloring-by-density for solids at some point.

Fix solid density color

---

media/src/App.svelte

Allows update for pinpoint poll without letting students pick more than one point at a time.

Replace pinpoint submission, don't make more

---

media/src/Panel.svelte
media/src/polls/Poll.svelte
media/src/polls/PollResponses.svelte
media/src/polls/Polls.svelte
media/src/session/Session.svelte

Possible add-ons:
- Currently objects are not transferred with their color, but that can be added.
- More descriptive submission feedback for students

make Object poll

---

media/src/App.svelte

This also appears to fix the orthographic camera bug.

Remove unused OutlinePass code

---

media/src/About.svelte
media/src/Intro.svelte
media/src/Panel.svelte

The actual text here isn't final, just getting this re-organization started.

Shorten Intro, make About page

---

mathplayground/rooms/consumers.py
media/src/App.svelte
media/src/Panel.svelte
media/src/polls/PollResponses.svelte
media/src/polls/Polls.svelte
media/src/polls/utils.js
media/src/session/Session.svelte

There are many cases to consider when adding this feature. The basics are in place for multiple choice, numeric poll, and object selection poll types.
Also, note that the poll results themselves aren't in the best shape at the moment and absolutely deserve some styling attention, which we can handle separately from these changes.

Add "Broadcast poll results" feature

---

media/src/Panel.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/Point.svelte
media/src/objects/Solid.svelte
media/src/objects/Surface.svelte
media/src/objects/Vector.svelte

The color can always be modified to fit out liking. Possible next steps: 
- Restrict random or user defined colors to avoid the color range near `selectedColor`
- Modify opacity, more object dependent
- Bounding Box

Implement a color change on select.

---

media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/ObjHeader.svelte
media/src/objects/Point.svelte
media/src/objects/Solid.svelte
media/src/objects/Surface.svelte
media/src/objects/Vector.svelte

Also implemented the hide object feature for the `Solid` object.
Only selected objects can be hidden with the Backspace key, but any object can be hidden/revealed if you click on the eye button even if you are not selected on it.
Closes #430

Hide object button implemented

---

media/mathplayground/global.css
media/src/Panel.svelte

Constrain custom nav-link color to Panel component, specifically the Info box, and remove custom visited `<a>` tag color.

Minor css adjustments

---

media/src/Panel.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/Point.svelte
media/src/objects/Solid.svelte
media/src/objects/Surface.svelte
media/src/objects/Vector.svelte

Decided to hard code the values since different objects use different opacity.

Highlight via opacity

---

media/src/objects/Solid.svelte
media/src/objects/Surface.svelte
media/src/settings/ColorBar.svelte
media/src/settings/Settings.svelte
media/src/stores.js
media/src/utils.js

Bouncing off #602, we can set colormaps (separately) for the density function (only applies to `Solid` and `Surface` of course).

Add colormaps to density fns

---

media/src/Panel.svelte

Use native CSS resizer on panel. This simplifies the code overall.
Unfortunately, it does require a special listener to place the panel-hider button properly, as we need to know the exact panel width when the panel is hidden in order to keep relative positioning here.

Remove custom panel resizer

---

media/src/objects/Surface.svelte

Parametric surfaces did not remove mousemove listener on shift keyup.

Fix shift tangent surface

---

media/src/App.svelte
media/src/Panel.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/Point.svelte
media/src/objects/Solid.svelte
media/src/objects/Surface.svelte
media/src/objects/Vector.svelte

See documentation for expected behavior: https://docs.google.com/document/d/1RL_HhJcSf4EtOuGAZM0VpecmmZba-6E7gsWC7AfTn1U/edit#heading=h.uzfzqk6m7elt

Behavioral changes to the keyboard controls

---

media/src/Panel.svelte
media/src/docs/HowTo.svelte

https://getbootstrap.com/docs/5.3/forms/select/

Use bootstrap select styles

---

media/src/App.svelte
media/src/settings/Settings.svelte
media/src/settings/offclick.js

Enabled the camera canvas-capture button (quite hacky, I should find the forum post I originally found). 
Also, made the settings/upload dialogs close on click elsewhere.

Screencap and offclick action

---

media/src/stories/FluxIntegral.svelte

Mostly rearranging, explaining, and styling. Added UI for sample point placement. (Corner better for explaining; center better for animating.)

Clean exposition/layout

---

media/src/settings/Settings.svelte
media/src/settings/WindowHeader.svelte

Decided to break up the accessibility updates into smaller PRs

Focus jumps to the chosen menu and back if the 'X' button is clicked.

---

media/src/settings/Settings.svelte

Scene JSON files that store color info were ignored. 
Also, objects with same UUID as incoming will be overwritten. 
TODO: 
- Prompt user to overwrite/append/ignore duplicates (and possibly keep preference)
- Fill in sensible color for objects without.

Upload color

---

media/src/objects/Function.svelte

Re-render on hide surface

---

mathplayground/settings.py

This is not necessary for this application.

Remove clickjacking middleware

---

media/src/form-components/PlayButtons.svelte
media/src/stories/PathIntegral.svelte

Path integrals

---

media/src/App.svelte
media/src/Panel.svelte
media/src/Story.svelte
media/src/docs/HowTo.svelte
media/src/settings/Settings.svelte
media/src/stores.js
media/src/utils.js

For embedding mostly. Checks query string for `showPanel=false` and hides panel by default.

Hide panel in query string

---

media/src/App.svelte

Fix initial font size

---

media/src/objects/Field.svelte

Make `vfscale` reactive to grid scale changes.

Bug fix. Correct arrow scaling in field

---

media/src/Story.svelte
media/src/stories/SurfaceArea.svelte
media/src/utils.js

Add the surface area story component.

Surface area story

---

media/src/App.svelte
media/src/Panel.svelte
media/src/Story.svelte
media/src/polls/Poll.svelte
media/src/polls/PollResponses.svelte
media/src/polls/Polls.svelte
media/src/session/Session.svelte
media/src/settings/Settings.svelte
media/src/stores.js
media/src/stories/ArcLength.svelte
media/src/stories/FluxIntegral.svelte
media/src/stories/PathIntegral.svelte
media/src/stories/SurfaceArea.svelte
media/src/utils.js

Closes #432.
Closes #736.
Big change is moving main objects array into `demoObjects` store. Allows reactivity in stories so, among, other things, deleting objects cues story to delete auxilliary objects from scene.
Added computation to/cleaned up Flux Integral story.

Storize objects array

---

media/src/Panel.svelte

Simple fix. Don't know how this bug stayed hidden this long.

Ignore keydown on inputs

---

media/src/App.svelte

What it says on the tin. `grid=true` now valid search parameter

Fix grid bug in search params

---

media/src/Panel.svelte

Round default values to tenths for easier exercises for vectors and points.

Simplify randomness in defaults

---

media/src/App.svelte
media/src/utils.js

Allow animations to be triggered in URL search string.

Add animation flag to search string

---

requirements.txt

Revert "Bump python-dateutil from 2.8.2 to 2.9.0.post0"

---

package-lock.json

Revert "⬆️ Bump @babel/preset-env from 7.24.1 to 7.24.3"

---

media/src/App.svelte
media/src/Panel.svelte

Revert "Encoding URL query with Base64"

---

package-lock.json

Revert "Revert "⬆️ Bump @babel/preset-env from 7.24.1 to 7.24.3""

---

media/src/App.svelte
media/src/Panel.svelte

Revert "Revert "Encoding URL query with Base64""

---

media/src/App.svelte
media/src/Panel.svelte

Rollback the encoding update until Drew is ready to make the change

---

requirements.txt

https://github.com/ccnmtl/3demos/security/dependabot/41

Updated sqlparse to patch a security vulnerability

---

media/src/objects/Solid.svelte

Solids need not be transparent.

Change material to opaque

---

media/src/App.svelte
media/src/Panel.svelte
media/src/utils.js

This is meant to use Base64 for encoding the scene into the URL. It does accept the old form (via a `try`/`catch`). 
URLs do get long. Here is a test one:
```[hostname]/?Y3VycmVudENoYXB0ZXI9SG93K1RvJnNjYWxlPTAmc2hvd1BhbmVsPWZhbHNlJm9iajBfa2luZD1zdXJmYWNlJm9iajBfY29sb3I9JTIzNTgwMWE1Jm9iajBfcGFyYW1zX2E9LTEmb2JqMF9wYXJhbXNfYj0xJm9iajBfcGFyYW1zX2M9MCZvYmowX3BhcmFtc19kPTIrcGkmb2JqMF9wYXJhbXNfeD11Jm9iajBfcGFyYW1zX3k9MSslMkIrLjIrKitleHAlMjgtJTI4dSstKzElMkYzJTI5JTVFMiUyOSsqK2NvcyUyOHYlMjkmb2JqMF9wYXJhbXNfej0xKy0rLjIrKitleHAlMjgtJTI4dSstKzElMkYzJTI5JTVFMiUyOSsqK3NpbiUyOHYlMjkmb2JqMF9wYXJhbXNfdDA9MCZvYmowX3BhcmFtc190MT0xJm9iajFfa2luZD1zdXJmYWNlJm9iajFfY29sb3I9JTIzZjY4ZTQ1Jm9iajFfcGFyYW1zX2E9MCZvYmoxX3BhcmFtc19iPTIqK3BpJm9iajFfcGFyYW1zX2M9MCZvYmoxX3BhcmFtc19kPTEmb2JqMV9wYXJhbXNfeD10KyUyQislMjgxKy0rdi …
```

Use base64 for url encoding

---

media/src/App.svelte

Closes #1033. Set the ambient light intensity to 50, and pointLightIntensity to 600. This setting matches the graph colors to the color selector.

Fix intensity values

---

requirements.txt

Corresponds to this alert: https://github.com/ccnmtl/3demos/security/dependabot/51

High security patch for 'twisted'

---

media/src/objects/Curve.svelte

The fields for x, y, z components can accept input "a", a constant that we can adjust with the slide bar.
[Local link example](http://localhost:8000/?Y3VycmVudENoYXB0ZXI9SG93K1RvJnNjYWxlPTAmc2hvd1BhbmVsPXRydWUmb2JqMF9raW5kPWN1cnZlJm9iajBfY29sb3I9JTIzMGQwODg3Jm9iajBfcGFyYW1zX2E9MCZvYmowX3BhcmFtc19iPTYqcGkmb2JqMF9wYXJhbXNfeD1jb3MlMjh0JTI5Jm9iajBfcGFyYW1zX3k9c2luJTI4dCUyOSZvYmowX3BhcmFtc196PWEqdCZvYmowX3BhcmFtc19hMD0wJm9iajBfcGFyYW1zX2ExPTI=).

add "a" dependence for space curves

---

media/src/App.svelte
media/src/Panel.svelte
media/src/objects/Curve.svelte
media/src/objects/Field.svelte
media/src/objects/Function.svelte
media/src/objects/Level.svelte
media/src/objects/Point.svelte
media/src/objects/Solid.svelte
media/src/objects/Surface.svelte
media/src/objects/Vector.svelte
media/src/settings/Kbd.svelte
media/src/settings/Settings.svelte
media/src/settings/WindowHeader.svelte
media/src/settings/offclick.js
media/src/stores.js

Add a menu with available shortcuts for objects in scene. 
Also, make `r` (rewind) behavior more uniform on a few objects.
Todo: Menu should display better at extreme (and mobile) views. Overflow (for large numbers of objects in scene) needs better handling.

Keyboard shortcut guide

---

mathplayground/settings_production.py
mathplayground/settings_staging.py

This application didn't have sentry set up at all, in fact.

Introduce init_sentry

---

media/src/Panel.svelte

Fix the binding on the `showPanel` option.

Fix showpanel from url

---

media/src/objects/Function.svelte
media/src/objects/Surface.svelte

The resolution was too damn high. 🤦‍♀️
Fixes #1372.

Fix resolution

---

media/src/stories/Blank.svelte
media/src/stories/FluxIntegral.svelte
media/src/stories/PathIntegral.svelte
media/src/stories/SurfaceArea.svelte

Parametric surfaces story was broken in upgrade to Svelte 5. Much more efficient now.

Fix parsurf story formulas

---

media/src/js-colormaps.js
media/src/stories/SurfaceArea.svelte

Fix buffer overflow on top end of density range.

Fix top end of color scale

---

package-lock.json

Revert "Bump mocha from 11.1.0 to 11.2.2"
