ccnmtl/3demos

- package-lock.json
- package.json
I'm not sure what this plugin does, but the v4 upgrade seems to cause the rollup build to hang. Let's downgrade this for now.
> Downgrade rollup-plugin-css-only to 3.1.x

- .github/workflows/build-and-test.yml
In my environment, the rollup build seems to be hanging. Errors like this should be caught automatically in github actions and/or jenkins.
> Test JS build on github actions

- rollup.config.js
Now that we're using the django back-end we don't need to serve this through rollup.
> Remove rollup's serve configuration

- media/src/App.svelte
This makes the grid lines a little clearer.
> Adjust shaderPass resolution

- media/src/Curve.svelte
This fixes a three.js warning:
> THREE.TubeBufferGeometry has been renamed to THREE.TubeGeometry.
The BufferGeometry stuff used to be in three.js as a more performant but also more complicated version of the standard Geometry class, but it looks like these have been removed.
> use TubeGeometry instead of TubeBufferGeometry to fix warning

- media/src/App.svelte
This fixes a problem adding objects outside of a room.
> Box rendering: don't use socket if it doesn't exist

- media/src/App.svelte
We found the FXAA shader behaves differently on different screens, and causes things to run slower. I think it's unnecessary for now.
> Remove unused FXAA stuff, and turn on webgl antialiasing

- mathplayground/asgi.py
- mathplayground/rooms/consumers.py
- mathplayground/rooms/views.py
- mathplayground/settings.py
* Configured redis for session storage
Because we're not planning on using a database or django auth here, I'm thinking we can use the session mechanism to store data for anonymous browser sessions.
This fixes the bug where objects are created twice in the author's environment when sending out a websocket update.
> Use session_key to determine socket sender/receiver

- .eslintrc.js
- package-lock.json
- package.json
- rollup.config.mjs
I removed the 'rollup-terser' plugin for now. This plugin is unmaintained, and doesn't support rollup 3. It's best to not rely on random packages like this - we can find a more standard way to minify the production build when necessary.
> Update to rollup v3

- mathplayground/rooms/consumers.py
- mathplayground/settings.py
Two things here:
* Change the channel type we're currently using to "graph_event". We may have other event types in the future.
* Adjust redis prefix used by channels to include the project name. Currently it's just "asgi", which should be fine as this is the only project that's currently using asgi in redis, but that's kind of generic.
> Some minor channels adjustments

- requirements.txt
redis-py recommends using hiredis. https://github.com/redis/redis-py#installation This change installs the package with hiredis support, which is a minimal redis client.
> Use hiredis if available

- mathplayground/rooms/scene.py
- mathplayground/rooms/views.py
Leave the state as a JSON string when using it to populate the window.SCENE_STATE javascript variable.
This should fix a problem I found on production, where the Python `None` keyword is used like this, which isn't valid javascript:
window.SCENE_STATE = {'objects': [{'uuid':
'e7e7a38a-66a3-4159-a876-022013001692', 'kind': 'curve',
'params': {'a': '0', 'b': '2*pi', 'x': 'cos(t)', 'y':
'sin(t)', 'z': 'cos(5*t)', 'tau': 0, 'color': '#0009a7'}},
{'uuid': '883f4224-1a5d-4a02-b227-8026826b3364', 'kind':
'box', 'params': None}]};
> RedisScene.get_state: add parse_json option

- media/src/App.svelte
Currently, a SCENE_STATE like this can crash the application:
```
[
{"uuid": "883f4224-1a5d-4a02-b227-8026826b3364", "kind": "box", "params": null}
]
```
See https://mathplayground.ctl.columbia.edu/rooms/4/ for a live example of this bug.
This change fixes that. Going forward, maybe this calls for some sort of loadScene() function that filters out bad data like this with robust validation and tests. This is related to Evan's work so I will hold off on that for now.
> Don't try to render boxes that don't have params set

- media/mathplayground/global.css
- media/src/App.svelte
- media/src/objects/Curve.svelte
- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Level.svelte
- media/src/objects/ParSurf.svelte
- media/src/objects/Vector.svelte
We should be relying on bootstrap for these standard styles, with less custom CSS for standard elements.
> CSS cleanup: remove some global button styles

- media/src/objects/Vector.svelte
- media/src/utils.js
Older but recent versions of Safari (e.g. 14.1.1) don't support Object.hasOwn():
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility
The `in` keyword has wider support:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in#browser_compatibility
> Don't use Object.hasOwn()

- media/src/objects/Curve.svelte
- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Level.svelte
- media/src/objects/ParSurf.svelte
Assigning to a new variable doesn't clone a javascript object. This was my mistake - we need to clone this in a different way: Object.assign() is a good way to do this.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
> Fix params cloning in params updater

- mathplayground/rooms/consumers.py
Don't overwrite scene data like host on the broadcastPoll websocket event.
> preserve scene state on broadcastPoll event

- media/src/App.svelte
This fixes the JS warning:
> `<Vector>` was created with unknown prop 'gridMax'
> Remove unused gridMax property from Vector

- media/src/App.svelte
The flip menu was interfering with canvas interactions. The inactive side of the flip was still interactive and any invisible elements that extended down further than the visible menu would prevent canvas interactions. You could even click invisible buttons.
We can restore the flip aesthetic, but that is purely Marc and Drew's domain. I'd recommend against it though. As it stands I would actually recommend restructuring `App.svelte`. There are some accessibility issues that are being overlooked for the sake of bug fixes and getting the MVP out ready. Though now that the elements are hidden that may improve tab navigation.
> Disabled css menu flip

- media/src/form-components/ObjectParamInput.svelte
- media/src/objects/Curve.svelte
- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Level.svelte
- media/src/objects/ParSurf.svelte
- media/src/objects/Vector.svelte
Taking out some of the magic of svelte here because the automatic two-way data binding for form inputs is problematic. The value should only be updated on blur.
Next steps here are:
* Add error handling for those that require mathJS parsing
> Introduce ObjectParamInput to object types

- media/src/App.svelte
The containing element's focus events aren't that reliable for determining focus: it's possible to permanently disable the controls like this:
* Add object to the scene
* Remove object
This fixes that by explicitly enabling controls in this scenario.
Also, we don't need to touch the `controls2` instance - I'm not sure what that's used for but we're only listening for key events on `controls`.
> Fix bug where controls are disabled after removing object

- media/src/form-components/ObjectParamInput.svelte
- media/src/objects/Curve.svelte
- media/src/objects/Function.svelte
- media/src/objects/Vector.svelte
Here's a scheme we can use to display errors to the user when mathjs evaluation fails, and not crash the scene. The UI is using bootstrap's form validation `is-invalid` error state. https://getbootstrap.com/docs/5.3/forms/validation/#server-side
I created two tickets for this that are basically the same issue:
#296 #295 
I'll implement this for the rest of the objects wherever makes sense now.
> Add mathjs input error handling

- media/src/form-components/ObjectParamInput.svelte
- media/src/objects/Curve.svelte
- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Level.svelte
- media/src/objects/ParSurf.svelte
- media/src/objects/Vector.svelte
As Drew pointed out, the change event doesn't actually fire on each keypress, it actually happens on blur. This is closer to what we want. Also, it looks like the browser fires the change event when Enter is pressed as well, which is also what we want.
> ObjectParamInput: use change event instead of blur

- package.json
Our use of this package was removed in this PR:
https://github.com/ccnmtl/mathplayground/pull/287
> Remove unused svelte-preprocess package

- media/src/objects/Function.svelte
This fixes a bug where the JS can crash by introducing a parse error into the main function, e.g. mis-matched parentheses. Just delete the final paren from the default expression and press enter, to reproduce this bug.
These changes fix that, and allow the error to be displayed properly to the user.
> Function Graph object: fix parse error in main function

- media/src/rooms.js
Sockets are closed when the user navigates to a new URL route, so, this isn't really "unexpected" at all.
> makeSocket: remove onclose handler - closes #324

- media/src/App.svelte
Resolves #307.
I incorporated the good ideas in #312 but the issue was a little subtle. Canvas elements are not focusable, for one, by default so it needed a tabIndex, but the `mousedown`/`up` event didn't need that anyway. Instead, I moved the keydown listeners for the controls to the canvas element, and then made a `$:` statement to give it focus whenever the shade goes up. 
@Evan-CTL might I have messed with keyboard accessibility? For one, using the Alt+space shortcut to lower the shade does not take focus from the canvas but clicking does.
> More canvas focusing

- requirements.txt
The jenkins build is failing with this error, since the typing-extensions upgrade:
> selenium.common.exceptions.WebDriverException: Message: unknown error:
> unable to discover open pages
I want to see if this revert fixes the issue.
reverts 940d46044a29076e5af27173634e23f41506c79b
> downgrade typing-extensions

- rollup.config.mjs
Like it says on the tin. Easier to read console logs/errors. 
I did switch the tag on the commonjs plugin which was **only** including the sourcemap on production builds. Seemed backward, no?
> Add sourcemap(s) for dev build

- media/src/App.svelte
- media/src/objects/Curve.svelte
- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Level.svelte
- media/src/objects/ParSurf.svelte
- media/src/objects/Vector.svelte
Two changes here:
* Rename main `selection` state variable to `selectedObject` to be more clear
* Don't pass uuid into the object - we can determine if it's selected outside the object and pass in that boolean
> Adjust object selection code

- media/mathplayground/global.css
The visual representation wasn't working. The border property probably got duplicated during a rebase/merge. Fixed it now
> CSS fix: .boxItem['border'] duplicate

- media/src/polls/Polls.svelte
- media/src/polls/utils.js
For example, in a private tab.
These changes fix this error:
> Fix crash when loading app with no polls in localStorage

- media/src/objects/Level.svelte
- media/src/objects/levelWorker.js
Specifically, to the g and k fields. This required some refactoring as the parsing is happening within the promise that starts off the calculations.
> Add mathjs eval validation to Level Surface - closes #363

- mathplayground/main/views.py
- mathplayground/rooms/consumers.py
- mathplayground/rooms/scene.py
- mathplayground/rooms/urls.py
- mathplayground/rooms/views.py
- mathplayground/settings_production.py
- mathplayground/settings_staging.py
- mathplayground/templates/index.html
- media/src/modes/Session.svelte
- media/src/rooms.js
Closes #356
Some unit tests for this new form code are in order, but this is working as is and gets rid of the extra socket connection when making a room.
Django >4.1 requires CSRF_TRUSTED_ORIGINS to be set for csrf to work in form POSTs. So this will need to be added the the `mathplayground/local_settings.py` file in your development environment:
```
CSRF_TRUSTED_ORIGINS = [
'https://your.url.columbia.edu'
]
```
> Handle makeRoom with basic form POST

- media/src/App.svelte
- media/src/objects/Function.svelte
- media/src/sceneUtils.js
Each 3demos object has a `uuid` we can use to determine what three.js meshes belong to which "object" created by our UI.
These changes add a new onRenderObject/onDestroyObject api we can use to keep track of the visible three.js meshes in the scene, and how they correspond to the 3demos object created by the user.
Next steps:
* Add this to the rest of the object types
* Add visual indicator that object is selected. Something that will work for all object types like a box around the object. Currently we just have the box in the Object list. Maybe take design cues from Blender: https://docs.blender.org/manual/en/latest/scene_layout/object/selecting.html
Issue #391
> Implement scene object hover/selection for Function object

- media/src/App.svelte
This fails open, meaning that if a student leaves the page before submitting they aren't locked out of the poll. If a student submits and refreshes the page then the poll will reappear but the submission will not count.
It could be set to accept the last poll submitted by each student, but I wasn't sure if Drew wanted students changing their answers at the last second for one reason or another. After all they aren't being graded. There are no consequences for getting it wrong.
> Prevent users from answering multiple times

- media/src/App.svelte
Closes #405
Without the initial `render()` call, the `<canvas>` element was getting a very low default size (300px), but still rendering the scene as well as it could. So, this is why it looked like my favorite space simulation game for MS-DOS: Noctis http://mooses.nl/nice/about/
There were other issues at play here as well, like `currentControls` being undefined, initially.
> Fix bug where loading an animated scene displays low resolution

- media/src/App.svelte
Use default browser cursor styles when leaving the three.js canvas. This fixes a bug where the pointer style persists in certain cases in the info window.
> Reset cursor style when leaving three.js scene

- media/src/App.svelte
- media/src/utils.js
The main part here is putting `e.preventDefault()` in the specific key handlers. The alt key is used by many window managers and browsers, and we don't need to override all that behavior here: e.g. I use alt+number to switch browser tabs.
> Refactor alt key handler

- .editorconfig
- media/src/App.svelte
- media/src/form-components/PlayButtons.svelte
- media/src/objects/Surface.svelte
- media/src/settings/ColorBar.svelte
- objectExamples/parsurfExample.json
- objectExamples/variousExample.json
Bunch of updates for `ParSurf`:
- rename component to `Surface` to align with others being plain words
- **new** add dynamic response to $t$-dependence
- **new** add colorization based on "density" scalar function. 
Try this query string: 
```
?currentChapter=Intro&flipInfo=true&shadeUp=true&obj0_kind=surface&obj0_color=%23680076&obj0_params_a=0&obj0_params_b=3+%2F+2*pi&obj0_params_c=pi&obj0_params_d=5*pi+%2F+2&obj0_params_x=cos%28u+%2B+t%29*%281+%2B+%281+%2B+sin%282t%29+%2F+2%29*sin%28v%29%2F3%29&obj0_params_y=sin%28u+%2B+t%29*%281+%2B+%281+%2B+sin%282t%29+%2F+2%29*sin%28v%29%2F3%29&obj0_params_z=-%281+%2B+sin%282t%29+%2F+2%29*cos%28v%29%2F3&obj0_params_f=x+%2F+10&obj0_params_t0=0&obj0_params_t1=2+pi
```
To jazz it up, select "Density" and enter a fun function like "sin(3*x)". Animate …
> Colormaps for surfaces

- media/src/App.svelte
The fontawesome upgrade caused this button to disappear, and we can unify some of the styles here in a better way.
> Refactor scene styles to fix "Leave Room" display

- mathplayground/main/views.py
This is a quick fix to fix the bug that can be reproduced with these steps:
1. open 3demos in private tab
2. click Session -> Make Room
User will be Student rather than Host.
Django doesn't create the user's session by default. We created this explicitly in the room view, but not the index view, causing this bug.
There may be a nicer fix to enable this globally, but for now this works.
> Fix bug where first "Make room" creates room as student

- mathplayground/main/views.py
Minor adjustment for my fix for session creation: we currently only use the session when the user wants to make a room. So, only create one on the form POST.
This way, the fix is still in place, but session stuff won't be touched at all if the user isn't touching the session functionality.
> Only create session when necessary

- media/src/objects/Solid.svelte
- media/src/objects/Surface.svelte
- media/src/settings/Settings.svelte
- media/src/stores.js
Make vmin/vmax consistent across objects. 
Basically just expands the range to encompass all objects using the density function. Reset button in Settings reverts to (-1, 1) but can be instantly overwritten if larger values present. Not sure if this is optimal for user. 
TODO:
- Style/bootstrapify elements in the Settings box. (Make reset an icon, maybe?)
> Make vMin/vMax universal

- media/src/objects/Level.svelte
- media/src/polls/Poll.svelte
- media/src/polls/PollForm.svelte
- media/src/session/Session.svelte
Unify the form-control inputs: not all of them were using `form-control-sm`.
> Bootstrap form input adjustments: use smaller inputs everywhere

- requirements.txt
https://www.djangoproject.com/weblog/2023/apr/03/django-42-released/
> :arrow_up: django 4.2

- media/src/Panel.svelte
- media/src/settings/Settings.svelte
- media/src/settings/WindowHeader.svelte
I don't think forcing the size is good practice, but I didn't want to devote more time to a minor styling issue. Rem at least scales with the character dimensions so it is accessible with zoom.
> Forced width on setting window

- media/src/settings/Settings.svelte
This addresses an issue that happens when extra settings icons are active, like when in a room.
> Only set width for settings modal box, not settings tray

- media/src/Panel.svelte
This doesn't make any real functional changes that I'm aware of. I just noticed these styles aren't necessary, so I'm removing them in the interest of simplifying things as we work to address #486 and possibly the pinned accordion item headers functionality that's been mentioned before as well.
https://getbootstrap.com/docs/5.3/utilities/flex/
> cleanup: Remove unused panel flexbox styles

- media/src/objects/Surface.svelte
Bug fix. 
`backMesh` wasn't visible when `chooseDensity` is false.
> Restore visibility to backMesh

- media/src/polls/Poll.svelte
We're using a string as the poll type instead of a number.
> Fix input display for numeric poll type

- media/src/objects/Curve.svelte
- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Level.svelte
- media/src/objects/Point.svelte
- media/src/objects/Solid.svelte
- media/src/objects/Surface.svelte
- media/src/objects/Vector.svelte
Strict equality is easier to reason about and in practice, I haven't found a use for loose equality. I suppose it's worth refreshing my memory on, though:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness
> Use triple-equals for comparison

- media/src/utils.js
Flat faces of solids could not be colored correctly with a density function as they only had vertices on the edges. This "fills in the gaps". 
For example, try a density function with rapid oscillations like `sin(5 * pi * sqrt(x^2 + y ^2 + z^2))` (where level sets are concentric spheres:
Before:
After:
> Fix solid density

- media/src/Panel.svelte
- media/src/docs/Badge.svelte
- media/src/docs/DocKeyControls.svelte
- media/src/docs/DocObjWindow.svelte
- media/src/docs/DocPolling.svelte
- media/src/docs/DocSession.svelte
- media/src/docs/HowTo.svelte
- media/src/docs/Intro.svelte
Addresses #486 (and closes #605). See discussion there for how I couldn't get the bootstappy dropdowns to escape their parent container. 
Here, both are swapped for old-fashioned `select` elements. There may be downsides besides being less stylable that I don't know about. Please test before merging. 
This ended with more refactoring than I expected, some like the add object code I like. Some, like the `Badge` component, less essential.
> Make panel `fit-content`able

- media/src/App.svelte
- media/src/Panel.svelte
- media/src/objects/Curve.svelte
- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Level.svelte
- media/src/objects/Point.svelte
- media/src/objects/Solid.svelte
- media/src/objects/Surface.svelte
- media/src/objects/Vector.svelte
- media/src/sceneUtils.js
In an attempt to close #425, I started messing around with the selection indication. Here is a temporary "flash" of the objects. ~This only is applied to `surface` objects at the moment,~ so add a few and play with selecting different combinations. 
Looks smoother in rendering than in the gif below. Do note the autoscrolling objects window. 
TODO:
- ~Play with the timing/intensity (consider epilepsy)~
- ~Reflash on duplicate/multiple selection (right now just reactive to `selected` being set to `true` in the component).~
- ~Add to other objects~
> Flash selection and autoscroll

- media/src/docs/DocKeyControls.svelte
The Escape key was remapped to 'h' to toggle the panel, here: https://github.com/ccnmtl/3demos/pull/621/files#diff-2235248ad737318f83b794277a0d675ea193e27942e1d9913c21de6f17f791b0R292
> Update documentation for menu hiding

- media/src/Panel.svelte
- media/src/docs/About.svelte
It looks like these need to start with `./` to get the path correct. This could be documented better.. or the behavior of the function changed. Not a high priority, though.
> Fix joinUrl calls

- media/mathplayground/global.css
I think the intention here was to set the font-size to 1.2rem. But default font size should generally be left up to the browser, as this makes things more flexible and customizable. See: https://getbootstrap.com/docs/5.2/content/typography/
> remove invalid css setting: "font: 1.2rem"

- requirements.txt
This library is unnecessary with newer versions of django-storages.
> Remove django-cacheds3storage

- media/src/Panel.svelte
`ceil`ed where one should have `floor`ed.
> Fix index bug on initialization

- media/src/App.svelte
Closes #898.
Animate loop was doing its own render without checking camera position. Could alter this to check if camera position has actually changed, but few enough labels to notice the difference at this point.
> Check axes labels in animate loop

- mathplayground/settings_production.py
- mathplayground/settings_staging.py
Rotate django logs when they meet 10mb.
Based on:
https://github.com/ccnmtl/ctlsettings/pull/24
> Configure log rotation

- mathplayground/settings_production.py
- mathplayground/settings_staging.py
3Demos might be running on a newer version of Python than ctlsettings. The Jenkins build could not find the `logging.RotatingFileHandler` so I've updated it to `logging.handlers.RotatingFileHandler` according to the current Python documentation.
> Update logging --> logging.handlers

- .gitignore
- media/src/Panel.svelte
- media/src/objects/Function.svelte
- media/src/objects/Point.svelte
- media/src/polls/Polls.svelte
- package-lock.json
- package.json
Migration to Svelte 4. [Migration script](https://svelte.dev/docs/v4-migration-guide) went through pretty cleanly. 
Moved from `@bestguy/sveltestrap` (required 3, not maintained) to [`@sveltestrap/sveltestrap`](https://github.com/sveltestrap/sveltestrap). 
Seems alright. Could need another check on "strappy" components.
> Migrate to Svelte 4

- media/src/App.svelte
- media/src/objects/Function.svelte
For graphs, suppress the controls for showing Riemann sums when not in use (using transitions). 
Add an opacity slider as well.
> Hide integration controls when not used

- mathplayground/templates/index.html
The SENTRY_DSN variable is no longer required using the new sentry-js loader config.
https://docs.sentry.io/platforms/javascript/install/loader/
> Introduce sentry JS config

- requirements.txt
Resolves this issue: https://github.com/advisories/GHSA-m9g8-fxxm-xg86
> Resolves an SQL injection vulnerability

- media/src/objects/Function.svelte
`$effect` rune runs too frequently because of other state changes. Only want to run once per frame. We untrack the other side effects. 
(Generally, there is too much `$effect`/`untrack` in here. Will look into refactoring later. Though triggered from multiple sources, it may not need to be reactive in this way.
> Run effect only on clock change

- media/src/objects/Field.svelte
- media/src/objects/Function.svelte
- media/src/objects/Surface.svelte
- media/src/objects/mathutils.js
For `Function`, `Surface`, and `Field`, "compile" math.js ASTs into regular JS functions. Gives a massive performance boost on dynamically (`t`-dependent) surfaces.
> Js quote unquote compiler

- media/src/objects/Function.svelte
- media/src/utils.js
Addresses #1172 by simply catching the error of nonconstant bounds and exiting. We should actually handle these properly in a Story, but that is for another day.
> Catch bound error

- media/src/objects/Curve.svelte
The `for` attribute on labels within the `Curve` components were exhibiting weird behavior when there was more than one instance. Clicking any only affected the first. Scrapping the `for` and enclosing the inputs seems to work.
> Fix label behavior for frame options
